version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2023-09-23T03-47-50Z.fips
    container_name: minio_server
    command: server --console-address ":9090" /data
    ports:
      - "9000:9000"
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=hangout-minio
    networks:
        - minio_network
  redis:
    image: bitnami/redis:6.2
    container_name: hangout_redis
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --loglevel warning --protected-mode no --save "" --appendonly no
    environment:
      - ALLOW_EMPTY_PASSWORD=yes


networks:
      minio_network:
